stages:
  - testing # Запуск тестов
  - history_copy # Копирование результата тестов из предыдущего запуска тестов
  - reports # Генерация отчета
  - deploy # Публикация отчета на gitlab pages


docker_job:
  stage: testing

  tags: 
    - mp-test 

  image: python:3.8-alpine

  before_script:
    - pip install -r requirements.txt
    - mkdir ./allure_results

  script:
    - pytest -m critical_path --url https://stores-tests-api.herokuapp.com -s  --alluredir=./allure_results

  allow_failure: true

  artifacts:
    when: always
    paths:
      - ./allure_results
    expire_in: 1 day

history_job:
  stage: history_copy

  tags:
    - mp-test

  image: storytel/alpine-bash-curl

  script:
    - 'curl --location --output artifacts.zip "https://gitlab.com/dimaklepikov/api/v4/projects/38958657/jobs/artifacts/master/download?job=pages&job_token=$CI_JOB_TOKEN"'
    - apk add unzip
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./allure_results

  allow_failure: true

  artifacts:
    when: always
    paths:
      - ./allure_results
    expire_in: 1 day

allure_job:
  stage: reports

  tags:
    - mp-test

  image: frankescobar/allure-docker-service

  script:
     - allure generate -c ./allure-results -o ./allure-report

  allow_failure: true

  artifacts:
    when: always
    paths:
      - ./allure_results
    expire_in: 1 day

pages:
  stage: deploy

  script:
    - mkdir public
    - mv ./allure_results/* public

  artifacts:
    paths:
      - public
  rules:
    - when: always